version: "3.9"

services:
  selenium-fastapi-dev:
    build:
      context: .
      target: dev
    hostname: selenium-fastapi-dev
    ports:
      - "${DOCKER_SELENIUM_PORT:-4404}:4404"
    volumes:
      - "./app:/app"
    # Force the container to stay alive
    tty: true

