version: "3.9"

services:
  selenium-fastapi-dev:
    extends:
      file: docker-compose.yml
      service: selenium-fastapi 
    hostname: selenium-fastapi-dev
    ports:
      - "${DOCKER_SELENIUM_PORT:-4404}:4404"
    volumes:
      - "./app:/app"
    # Force the container to stay alive
    tty: true

