version: "3.9"

services:
  selenium-fastapi: 
    build:
      context: "./"
      dockerfile: "Dockerfile"
      target: prod
      args:
        - PYTHON_VERSION
    hostname: selenium-fastapi
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - "${DOCKER_SELENIUM_PORT:-4404}:4404"
    tty: true
